### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by yav** [ZippeyKeys12/cerberus#3]
Consider the following example
```c
// Bad spec.
// The problem here is that the function does not dealloacte the pointer,
// but the `ensure` clause does return the ownership it took.

void f(int *p)
/*@
requires
  take unused_1 = Block(p);
ensures
  true;
@*/
{
  *p = 2;
}
```

Testing the code fails, as it should.  However the resulting error is quite confusing:
```
Using seed: ea46ff43455cf556
Testing ptr-02::f: FAILED
C memory access failed: function f, file cn-test-umBbZjO9/ptr-02-exec.c, line 42

Testing Summary:
cases: 1, passed: 0, failed: 1, errored: 0, skipped: 0
GENERATED: cn-test-umBbZjO9
```

The location that is referenced in the error simply points to "assert(true)", and it is quite unclear what memory access we are talking about.

**Comment by ZippeyKeys12** [comment]
All the checking of conditions is using the executable spec work. I believe better error messages and better locations are on their todo list
